### ISSUE TITLE
TODO things

### ISSUE THREAD

**Issue by sekunder** [sekunder/SWDB-KART#1]
- [ ] [Alex] Apply Fourier transform to natural images and to static gratings, save output in useful format
- [x ] [Alex and Kate] Extract useful information from Fourier transform: spatial frequency and, if possibly, orientation information.
  - [ ] [Alex] Ask Michael if it's possible to get orientation information from this shiz.
  - [ x] [Kate] Get to the bottom of what the output from the fourier transform function, as written, actually is.
- [ ] If orientation is not a thing, get it some other way from the natural images.
- [ ] [Rebecca] Build something to compare cells based on metrics from the first three TODO items.
- [ ] [Rebecca] Try to use Phil's cell list to select cells.
- [ ] [Torrey] Compare median and mean sweeps (for making selection of cells)
- [ ] [Errbody] Start thinking about what plots we want to have in our final presentation
  - [x] make sure they are both rad, and also sicknasty

@vrebex @torreydactyl @ChainFonda
